### ISSUE TITLE
titles support for NSLocalizedString or LocalizedStringKey

### ISSUE THREAD

**Issue by ghost** [yonat/RadioGroup#10]
**Description:**
titles support for `NSLocalizedString(<#T##key: String##String#>, comment: <#T##String#>)` or `LocalizedStringKey()`
**Problems I encountered when trying to implement this myself:**

**Comment by yonat** [comment]
@vmshaneeb You can pss localized strings to `titles` like this:

```swift
let radioGroup = RadioGroup(titles: [
    NSLocalizedString("First", comment: ""),
    NSLocalizedString("Second", comment: ""),
])
```
