### ISSUE TITLE
RadioGroup Items not shown correctly

### ISSUE THREAD

**Issue by gharary** [yonat/RadioGroup#21]
**Description of the problem:**
[description]
I have three items showing horizontally but sometimes they don't show correctly!

<img width="261" alt="Screen Shot 2021-07-10 at 11 21 39 PM" src="https://user-images.githubusercontent.com/16289125/125173723-e0290380-e1d5-11eb-926d-06309a0cf00f.png">
<img width="636" alt="Screen Shot 2021-07-10 at 11 24 10 PM" src="https://user-images.githubusercontent.com/16289125/125173734-f1721000-e1d5-11eb-8531-f35ab28237cf.png">

It's in a Vstack with some other items but as it is horizontal, some times it draw normal, sometimes draw like the image above!
**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
[link to a Minimal Reproducible Example as described at https://ootips.org/yonat/repex ]

**Comment by yonat** [comment]
The above code works fine for me, so I'll need running code that shows the problem.
Please **create a minimal project that reproduces this problem**, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by susonthapa** [comment]
I am also facing the same issue.
![image](https://user-images.githubusercontent.com/33973551/127292013-ce82c48f-dfbf-496c-b681-54174765914f.png)
Like in our case when both "Gender" and "Marital Status" is added this happens. But using only one of them works fine. 
![image](https://user-images.githubusercontent.com/33973551/127292687-ee22972b-9a99-496f-af32-4ab3f8a6f656.png)
Debugging with view debugger there is error saying "width is ambiguous.

**Comment by yonat** [comment]
@susonthapa please create a a minimal github project that has this problem, so I can try to find a solution. (See https://ootips.org/yonat/repex/)
