### ISSUE TITLE
Unselect current item

### ISSUE THREAD

**Issue by josipbernat** [yonat/RadioGroup#22]
**Description:**
Can you please add ability to unselect current selection? I see that control supports this with selectedIndex: -1 but if I tap on already selected item it doesn't unselect.

**Problems I encountered when trying to implement this myself:**
I tried to subclass RadioGroup but `func selectIndex(item: RadioGroupItem)` isn't open + `RadioGroupItem` is also internal.

Thanks!

**Comment by yonat** [comment]
Hmmm, that's not a standard behavior. I don't want to add something so different than the standard radio group behavior, sorry.

(See for example https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio)
