### ISSUE TITLE
 the thickness of the outer circle

### ISSUE THREAD

**Issue by EmreSURK** [yonat/RadioGroup#4]
**Description:**
Is it possible to change the border size? I mean, the thickness of the outer circle?

<img width="50" alt="thinnerCircle" src="https://user-images.githubusercontent.com/9450430/59276625-5c536480-8c67-11e9-92ea-abd952f6a27f.png">

**Comment by EmreSURK** [comment]
Edit; There is a ringWidth value for buttons, but I can't see that in the inspector and I can't reach value via RadioGroup object.

I believe some option like that could be nice;
`
radioGroup.wingWidth = 2 
`

**Comment by yonat** [comment]
Just updated to 1.2.3, now you can:

```swift
RadioButton.appearance().ringWidth = 2
```
