### ISSUE TITLE
Radio buttons are not distributed evenly.

### ISSUE THREAD

**Issue by quangctkm9207** [yonat/RadioGroup#6]
**Description of the problem:**
The buttons inside the radio group are not distributed equally. 
Even when I set the spacing.
```
radioGroup.spacing = 12
```
Can you help me to check this issue? Thanks!

<img width="318" alt="Screen Shot 2019-08-04 at 23 46 05" src="https://user-images.githubusercontent.com/5425265/62425100-2cc65300-b712-11e9-845f-3523c4869f68.png">

**Comment by yonat** [comment]
No code attached, so I’ll need to guess...
I see two options:

1. Remove the height constraint so the group height can be correct.
2. Increase the spacing to match the height constraint (but that may break when the screen size or font size changes).

**Comment by quangctkm9207** [comment]
Thanks for your response.

I would like to share the flow of how I set up the radio group.
1. Firstly, I created an UIView on Storyboard called radioGroupViewHolder.
2. Then, I added RadioGroup by codes.
`radioGroupViewHolder.addSubview(radioGroup)`

About your suggestion, it seems that it will not fix the root cause.
However, I will try with the 1st one.

**Comment by yonat** [comment]
If you don't set constraints, then the `frame` takes precedence. To set constraints, write:

```swift
radioGroupViewHolder.translatesAutoresizingMaskIntoConstraints = false
```

**Comment by yonat** [comment]
I made a fix that will keep the items equally spaced, but this spacing may be bigger than `spacing`.
I think a better solution is to use the intrinsicContentSize (ie do nothing) instead of setting a frame or height constraint.

**Comment by quangctkm9207** [comment]
Thank you @yonat a lot for your help!
