### ISSUE TITLE
Remove dependency SweeterSwift

### ISSUE THREAD

**Issue by 4brunu** [yonat/RadioGroup#7]
Hey,

First of all, thanks for the great library.

I would like to import only the library RadioGroup but not SweeterSwift.

Would it be possible to remove the dependency SweeterSwift?

Thanks

**Comment by yonat** [comment]
It's used in the code...
Does it cause problems for you?

**Comment by 4brunu** [comment]
Yes, I know, I was just wondering in case it's used in a small portion, if it could be removed.
Because I'm trying to keep my dependencies to a minimum.
But if you prefer to keep the dependency I understand your decision. 🙂

**Comment by maestrovsmaster** [comment]
extension Codable+Sweeter.swift   kill my day =(
Because init?(dictionary: [String: Any]) has conflict with my Model Decodable files...
This is bad approach!
It must be remote from code!

**Comment by yonat** [comment]
@maestrovsmaster After testing, it's clear that the app-defined `init` will be used, not the library. See test at https://github.com/yonat/SweeterSwift/commit/71adbd4a84379241efab40c4e0edd3dd6178126e .
