### ISSUE TITLE
Archive error 

### ISSUE THREAD

**Issue by prakashmaharjan** [yonat/RadioGroup#8]
I am using  RadioGroup via SwiftPackage Manager in my project with target iOS 10. Its all fine but when I try to archive project for submission, I get error as shown below:

<img width="1177" alt="sc1" src="https://user-images.githubusercontent.com/8100150/72662820-d5901280-3a13-11ea-94b1-a88db4f3a62d.png">

Is it due to SwiftUI code? My project is not a SwiftUI code as it targets from iOS 10.
Any suggestion or solution that could be helpful?
Thanks

**Comment by yonat** [comment]
Right, you'll need to use version 1.3.3 to avoid that.

**Comment by prakashmaharjan** [comment]
thank you..

**Comment by ricardofavero** [comment]
Same error here

Using SwiftUI
Targeting iOS 13.4
Using XCode 11.4.1

**Comment by yonat** [comment]
Please create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by CocoaPriest** [comment]
Same here. Installed via SPM, archiving fails. iOS 13.4, Xcode 11.7

**Comment by CocoaPriest** [comment]
Actually the problem was with: https://github.com/yonat/RadioGroup/blob/e8ddfcc10e7ed42815fa57936ac7ab5a17e266d1/Package.swift#L8
after changing it to `.v13` (SwiftUI availability) everything works.
